# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script:  wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

- script:  chmod +x codeql-runner-linux
  displayName: 'change permission on codeql-runner.'

- script: |
    ./codeql-runner-linux init --repository yhampl3/mulerepo --github-url https://github.com --github-auth 5ade1bafb8ef409d8b059e650ded17bcc7d714ff
  displayName: 'Initialize CodeQ Executable and create a CodeQL database'

- script: |
    ./codeql-runner-linux analyze --repository yhampl3/mulerepo --github-url https://github.com --github-auth 5ade1bafb8ef409d8b059e650ded17bcc7d714ff --commit --ref main
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'