# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

